add_newline = false

format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$golang\
$helm\
$java\
$nodejs\
$purescript\
$ruby\
$rust\
$swift\
$terraform\
$memory_usage\
$gcloud\
$env_var\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

[character]
error_symbol = "!"

[package]
disabled = false

[cmd_duration]
min_time = 1

[[battery.display]]
threshold = 10
style = "bold red"

